username=example
password=changeme
nic=eth0
module=rjv3
#internet-check=1
#internet-check-url=http://connect.rom.miui.com/generate_204
#internet-check-interval=60
#internet-check-timeout=3
#internet-check-max-fail=3
